version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: >
    #   sh -c "
    #   python manage.py makemigrations &&
    #   python manage.py migrate
    #   "
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development

  # nginx:
  #   image: nginx:1.25.5-alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - api