# Generated by Django 5.0.4 on 2024-05-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tutors.tutor'),
        ),
    ]
